### PR TITLE
Updated changelog.rst for 2.5.0 release

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
This should wait for #253 at least...

**Comment by do-rtk** [comment]
Just bumping this up as it's ready for release. It's blocking our py 3.12 test

**Comment by do-rtk** [comment]
@claudep I don't think `2.5.0` was ever deployed to pypi https://pypi.org/project/django-formtools/

**Comment by claudep** [comment]
No, it was not, because of https://github.com/jazzband/django-formtools/issues/260, but looks like few people are concerned by this package maintenance :disappointed:

**Comment by do-rtk** [comment]
Perhaps https://github.com/jazzband/django-formtools/pull/263 might help.
I'm not too familiar with buildtools but this seems to produce builds with actual version numbers. PTAL

**Pull request merged**
