### PR TITLE
Update suporrted versions

### PR DESCRIPTION
**Pull request by smithdc1**
- Added support for isort 5
- Updated supported Python and Django versions.

### CODE REVIEW

**Comment by claudep** [comment]
Thanks! Do you plan to merge commits (at least partly)?

**Comment by claudep** [comment]
It looks like classifiers in setup.py need an update too.

**Comment by smithdc1** [comment]
Hi @claudep :wave: 

Done and done :+1:

**Comment by claudep** [comment]
Thanks a lot!

**Pull request merged**
